env:
  global:
    - CC_TEST_REPORTER_ID=28f492072ba466aa072e7ee76a43459d2ba0f4833d16e87d153b90a0e86c52b1

language: go

go:
  - '1.10'
  - '1.12'
  - tip

# Setting sudo access to false will let Travis CI use containers rather than
# VMs to run the tests. For more details see:
# - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# - http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: false

before_install:
  - go get -t -v ./...

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
