version: 1

sequence:
  - step1
  - step2
  - step3

triggers:
  - i-any

fallback: global-feedback

outputs:
  step1:
    expectedInputs:
      i-yes: next
      i-no: end
    fallback: unexpected1
  unexpected1:
    expectedInputs:
      i-yes: step2
      i-no: end
    fallback: unexpected2
