version: 1

sequence:
  - welcome
  - weather-report

triggers:
  - i-user-welcome

fallback: clarification

outputs:
  welcome:
    expectedInputs:
      i-yes: next
      i-no: bye
    fallback: welcome-clarification